<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />

  <PropertyGroup>
    <AssemblyName>ScuffedAnticheatMod</AssemblyName>
    <TargetFramework>net6.0</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="tModLoader.CodeAssist" Version="0.1.*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Data.Sqlite">
      <HintPath>lib/Microsoft.Data.Sqlite.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="SQLitePCLRaw.batteries_v2">
      <HintPath>lib/SQLitePCLRaw.batteries_v2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="SQLitePCLRaw.core">
      <HintPath>lib/SQLitePCLRaw.core.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="SQLitePCLRaw.provider.e_sqlite3">
      <HintPath>lib/SQLitePCLRaw.provider.e_sqlite3.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <!-- <ItemGroup>
    <EmbeddedResource Include="lib\runtimes\alpine-arm\native\libe_sqlite3.so" />
    <EmbeddedResource Include="lib\runtimes\alpine-arm64\native\libe_sqlite3.so" />
    <EmbeddedResource Include="lib\runtimes\alpine-x64\native\libe_sqlite3.so" />
    <EmbeddedResource Include="lib\runtimes\browser-wasm\nativeassets\net6.0\e_sqlite3.a" />
    <EmbeddedResource Include="lib\runtimes\linux-arm\native\libe_sqlite3.so" />
    <EmbeddedResource Include="lib\runtimes\linux-arm64\native\libe_sqlite3.so" />
    <EmbeddedResource Include="lib\runtimes\linux-armel\native\libe_sqlite3.so" />
    <EmbeddedResource Include="lib\runtimes\linux-mips64\native\libe_sqlite3.so" />
    <EmbeddedResource Include="lib\runtimes\linux-musl-arm\native\libe_sqlite3.so" />
    <EmbeddedResource Include="lib\runtimes\linux-musl-arm64\native\libe_sqlite3.so" />
    <EmbeddedResource Include="lib\runtimes\linux-musl-x64\native\libe_sqlite3.so" />
    <EmbeddedResource Include="lib\runtimes\linux-ppc64le\native\libe_sqlite3.so" />
    <EmbeddedResource Include="lib\runtimes\linux-s390x\native\libe_sqlite3.so" />
    <EmbeddedResource Include="lib\runtimes\linux-x64\native\libe_sqlite3.so" />
    <EmbeddedResource Include="lib\runtimes\linux-x86\native\libe_sqlite3.so" />
    <EmbeddedResource Include="lib\runtimes\maccatalyst-arm64\native\libe_sqlite3.dylib" />
    <EmbeddedResource Include="lib\runtimes\maccatalyst-x64\native\libe_sqlite3.dylib" />
    <EmbeddedResource Include="lib\runtimes\osx-arm64\native\libe_sqlite3.dylib" />
    <EmbeddedResource Include="lib\runtimes\osx-x64\native\libe_sqlite3.dylib" />
    <EmbeddedResource Include="lib\runtimes\win-arm\native\e_sqlite3.dll" />
    <EmbeddedResource Include="lib\runtimes\win-arm64\native\e_sqlite3.dll" />
    <EmbeddedResource Include="lib\runtimes\win-x64\native\e_sqlite3.dll" />
    <EmbeddedResource Include="lib\runtimes\win-x86\native\e_sqlite3.dll" />
  </ItemGroup> -->

  <!-- <ItemGroup>
    <None Include="lib\runtimes\alpine-arm\native\libe_sqlite3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\alpine-arm64\native\libe_sqlite3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\alpine-x64\native\libe_sqlite3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\browser-wasm\nativeassets\net6.0\e_sqlite3.a">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\linux-arm\native\libe_sqlite3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\linux-arm64\native\libe_sqlite3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\linux-armel\native\libe_sqlite3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\linux-mips64\native\libe_sqlite3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\linux-musl-arm\native\libe_sqlite3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\linux-musl-arm64\native\libe_sqlite3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\linux-musl-x64\native\libe_sqlite3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\linux-ppc64le\native\libe_sqlite3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\linux-s390x\native\libe_sqlite3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\linux-x64\native\libe_sqlite3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\linux-x86\native\libe_sqlite3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\maccatalyst-arm64\native\libe_sqlite3.dylib">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\maccatalyst-x64\native\libe_sqlite3.dylib">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\osx-arm64\native\libe_sqlite3.dylib">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\osx-x64\native\libe_sqlite3.dylib">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\win-arm\native\e_sqlite3.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\win-arm64\native\e_sqlite3.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\win-x64\native\e_sqlite3.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\runtimes\win-x86\native\e_sqlite3.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup> -->
</Project>